### ISSUE TITLE
No container can run this application/Please ensure that you've pushed a valid JVM artifact or artifacts

### ISSUE THREAD

**Issue by HirenNag** [Service-Flow/java-buildpack-cloudfoundry#3]
I am getting below error while trying to puch my spring boot application on cloudfoundry.

**Java Buildpack v4.9 (offline) | https://github.com/cloudfoundry/java-buildpack.git#830f4c3
   [Buildpack]                      ERROR Finalize failed with exception #<RuntimeError: No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation. >
   No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation.
   Failed to compile droplet: Failed to run finalize script: exit status 1
   Exit status 223**

And here is my manifest.yml file

---
applications:
- name: Dimple-Hiren-App
  path: offerup_services/target/offerup_services-2.0.0.RELEASE.jar
  memory: 768M
  instances: 1
  random-route: true

Its a Spring boot web app. Not sure why the issues is. Even tried giving the java_buildpack as well but in vain. Any help?

**Comment by kvirkki** [comment]
@HirenNag This repository is a for of https://github.com/cloudfoundry/java-buildpack. You probably meant to add your issue there :)

Cheers,
-Kai
